### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tools/opt-out#43]
**Objective**
Set up pre-commit hooks, linters and automatic running of tests

**Description**

**Skills**
javascript

**Tools**
jest, jshint, husky?

**Time Estimation**

**Detailed description/notes**

**Comment by Haimchen** [comment]
There is a basic setup now that is running on each change on master.
TODO: Have it also run on PRs (from forks of the repo as well) so branch protection can be enabled on master.

Later on running the tests should also be added.

**Comment by Haimchen** [comment]
I did a bit of research and apparently I was wrong regarding the pre-commit hooks: They are only local, so if we wanted to include them for everyone, we would have to use another tool. 

To make it a bit easier I would propose to go with a simpler solution (and less dependencies:):
- set up Circle CI so that a failed build will block a PR merge (that needs to be done by someone with admin access to this repo and access to Circle CI). Als we need to set it up to accept PRs from forks, how to do that is in the [Circle CI Docs](https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories)
- Add a section in the README explaining how the branch protection is set up (requires CI checks to pass and at least 1 review)
- also add a note on how to set up a pre-commit hook locally or how to run the linter locally, so that a contributor can run the checks before creating the PR

**Comment by malteserteresa** [comment]
I think that sounds brilliant , I will update the branch protection scheme to add back the cirlce ci checks. 

Which package would you recommend for the local pre-commits?
